### ISSUE TITLE
When the screen is configured with an offset (usually in a multi-screen scene), the letters displayed are also offset and not displayed on the exact window.

### ISSUE THREAD

**Issue by liushuai05** [PostCyberPunk/easyfocus-hyprland#3]
My screen configuration is as follows:
```
monitor=HDMI-A-1,1920x1080@0,0x0,1,transform,1
monitor=DVI-D-1 ,1920x1080@60,100x500,1,transform,0
```

When I use easyfocus-hyprland under the DVI-D-1 screen, there is a prompt that the letter is not on the corresponding window
![微信图片_20240430120039](https://github.com/PostCyberPunk/easyfocus-hyprland/assets/26994692/570839ea-a6f6-4bea-aedc-984153ef9265)
![微信图片_20240430120054](https://github.com/PostCyberPunk/easyfocus-hyprland/assets/26994692/da1b2ff8-f7f8-4d4b-91bc-94be7185ccca)

**Comment by PostCyberPunk** [comment]
oops , i forgot to remove the offset from monitor.
被其他项目抓住了手脚...过两天修，可以pr

**Comment by liushuai05** [comment]
> oops , i forgot to remove the offset from monitor.
> 被其他项目抓住了手脚...过两天修，可以pr

感谢大佬 挺好用的 赞 可惜我不会r语音 要麻烦大佬了😂

**Comment by PostCyberPunk** [comment]
should be fixed now, @liushuai05
